#
# Common TXx9
#
core-$(CONFIG_MACH_TX39XX)      += arch/mips/txx9/generic/
core-$(CONFIG_MACH_TX49XX)      += arch/mips/txx9/generic/

#
# Toshiba JMR-TX3927 board
#
lib-$(CONFIG_TOSHIBA_JMR3927)  += jmr3927/

#
# Toshiba RBTX49XX boards
#
lib-$(CONFIG_TOSHIBA_RBTX4927) += rbtx4927/
lib-$(CONFIG_TOSHIBA_RBTX4938) += rbtx4938/
lib-$(CONFIG_TOSHIBA_RBTX4939) += rbtx4939/
