#
# Sibyte SB1250 / BCM1480 family of SOCs
#
core-$(CONFIG_SIBYTE_BCM112X)	+= sb1250/
core-$(CONFIG_SIBYTE_BCM112X)	+= common/
core-$(CONFIG_SIBYTE_SB1250)	+= sb1250/
core-$(CONFIG_SIBYTE_SB1250)	+= common/
core-$(CONFIG_SIBYTE_BCM1x55)	+= bcm1480/
core-$(CONFIG_SIBYTE_BCM1x55)	+= common/
core-$(CONFIG_SIBYTE_BCM1x80)	+= bcm1480/
core-$(CONFIG_SIBYTE_BCM1x80)	+= common/

#
# Sibyte BCM91120x (Carmel) board
# Sibyte BCM91120C (CRhine) board
# Sibyte BCM91125C (CRhone) board
# Sibyte BCM91125E (Rhone) board
# Sibyte SWARM board
# Sibyte BCM91x80 (BigSur) board
#
core-$(CONFIG_SIBYTE_CARMEL)	+= swarm/
core-$(CONFIG_SIBYTE_CRHINE)	+= swarm/
core-$(CONFIG_SIBYTE_CRHONE)	+= swarm/
core-$(CONFIG_SIBYTE_RHONE)	+= swarm/
core-$(CONFIG_SIBYTE_SENTOSA)	+= swarm/
core-$(CONFIG_SIBYTE_SWARM)	+= swarm/
core-$(CONFIG_SIBYTE_BIGSUR)	+= swarm/
